[package]
name = "skale-gasless"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["rustls"] }
tokio = { version = "1.28", features = ["full"] }
rand = "0.8"
rayon = "1.7"
num_cpus = "1.15"
parking_lot = "0.12"